### Site metadata ###

site_name: Treefmt Quickstart
site_description: Starter template for a MkDocs docs site on GH Pages - including CI
site_url: https://zimboflyman.github.io/mkDocs-setup/docs/

repo_url: https://github.com/zimboflyman/mkDocs-setup
edit_uri: edit/master/docs/docs

### Build settings ###
    
theme:
  name: 'material'
#  custom_dir: material/.overrides
#  palette:
#    primary: 'red'
#    accent: 'lightblue'
    
  palette:
    - scheme: default
      primary: teal
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    #- scheme: shanesDarkTheme
    - scheme: slate
      primary: blue grey
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
#     text: Montserrat
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/logo.png

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  
nav:
  - About the project: introduction.md
  - QuickStart:
      - About: quickstart.md
      - Installation: installation.md
      - Configuration: treefmt-configuration.md
  - Usage: usage.md
  - Formatters: 
      - About: index-formatters.md
      - Formatter Specification: formatters-spec.md
      - Known Formatters: formatters.md
  - FAQ: faq.md
  - Contributing: contributing.md
  
  # - Home: index.md
  # - About MkDocs: about-mkdocs.md
  # - Tutorial:
  #     - TL;DR: tutorial/tldr.md
  #     - Installation: tutorial/installation.md
  #     - Set up project: tutorial/setup-project.md
  #     - Advanced: tutorial/advanced.md
  #     - Usage: tutorial/usage.md
  #     - Deploy: tutorial/deploy.md

extra_css:
    - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/numtide
      name: NumTide on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/numtide
      name: NumTide on Twitter
  generator: false # hide the line "Made with Material for MkDocs"
      
copyright: Copyright &copy; 2023 NumTide
  
